version: '3.8'

services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - camagru_uploads:/var/www/html/public/uploads:ro
    depends_on:
      - backend
    networks:
      - camagru

  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - camagru_uploads:/var/www/html/public/uploads:rw
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - camagru

  db:
    container_name: camagru-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - camagru
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - camagru

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025" # Porta SMTP (dove PHP invia le mail)
      - "8025:8025"
    networks:
      - camagru
  
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "frontend:80"
    depends_on:
      - frontend
    networks:
      - camagru

volumes:
  db_data:
  camagru_uploads:

networks:
  camagru:
    driver: bridge