services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog
    container_name: camagru-mailhog
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Interfaccia Web

  adminer:
      image: adminer
      container_name: camagru-adminer
      ports:
        - "8081:8080"